### PR TITLE
some names were outdated

### PR DESCRIPTION
**Pull request by cinnamew**
sato doesn't teach at tino anymore, ms. purse goes by ms. joy now, 910 (possibly 906 too? i'm not sure tho) should be cooking i think (at least it was last year i'm not sure abt this year so i just added a comment)

### CODE REVIEW

**Review by solunian — APPROVED** [review]
cool cool cool

**Comment by solunian** [comment]
what's the athletic trainer room? is it like the weight training thingy?

Also, i didn't include stuff thats far from the main campus because i was lazy lol

**Comment by cinnamew** [comment]
no it's right next to the girl's locker room but yeah it'd go off the map a bit 😿

**Comment by solunian** [comment]
oh really? oh well lol 🤷

**Pull request merged**
